CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `password` varchar(35) NOT NULL,
  `loginkey` varchar(32) NOT NULL,
  `email` varchar(255) NOT NULL,
  `sex` int(1) NOT NULL DEFAULT '0',
  `regdate` int(1) NOT NULL,
  `birthday` date DEFAULT NULL,
  `from` varchar(255) DEFAULT NULL,
  `www` varchar(255) DEFAULT NULL,
  `messenger` varchar(255) DEFAULT NULL,
  `signature` text,
  `avatar` varchar(255) DEFAULT NULL,
  `settings` text,
  `points` int(10) NOT NULL DEFAULT '0',
  `notifications_new` int(5) NOT NULL DEFAULT '0',
  `notifications_count` int(5) NOT NULL DEFAULT '0',
  `pm_count` int(5) NOT NULL DEFAULT '0',
  `post_count` int(5) NOT NULL DEFAULT '0',
  `last_visit_time` int(10) NOT NULL DEFAULT '0',
  `last_update_time` int(10) NOT NULL DEFAULT '0',
  `warns` int(2) NOT NULL DEFAULT '0',
  `ban` int(1) NOT NULL DEFAULT '0',
  `bantime` int(10) NOT NULL DEFAULT '0',
  `admin` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
